### ISSUE TITLE
Takeover maintenance

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rscrypt#13]
Hey folks, 

Just doubling the message (I already e-mailed Andy).

This is off CRAN and I was just curious if the functionality merged into anything else (`keybase` has been relying on it).

If not, can I take over maintenance and get it back on CRAN?

thx,

-Bob

**Comment by kippandrew** [comment]
Bob,

We're not maintaining this package anymore, since we no longer use it. As a result, it's been archived from CRAN. I believe there was some issues that required fixing in order to get it back on CRAN. 

We're happy to to have the help maintaining it. Let me know how you would like to proceed. 

-Andy

**Comment by bobjansen** [comment]
Hi,

Another Bob chiming in. The package has been archived, anything I can do to bring it back?

Kind Regards,

Bob

**Comment by kippandrew** [comment]
Bobs,

This package was archived from CRAN because there was an issue compiling it. Unfortunately, we've stopped using this package internally, and because of that we've not dedicated the time to investigate what it would take to get this back on CRAN, nor is it likely we would do so in the near future. 

That said, I would happily accept and PR that brings this back up to date, and I can help get it resubmitted back to CRAN.

This is the last note I received about the issues compiling:

```
Your file util.cpp contains

static clock_t clocktouse;
...
     if (clock_gettime(clocktouse, ts))

but that is not the correct type (see
http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_gettime.html).
  MacOS 10.12 has added clock_gettime and hence your package fails to
install there:

util.cpp:75:9: error: no matching function for call to 'clock_gettime'
     if (clock_gettime(clocktouse, ts))
         ^~~~~~~~~~~~~
/usr/include/time.h:177:5: note: candidate function not viable: no known
conversion from 'clock_t' (aka 'unsigned long') to 'clockid_t' for 1st
argument
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
     ^
```

And also this note from Brian Ripley:

```
For the record, this contains a src/scrypt-1.1.6/configure produced by
autoconf but no configure.{ac.in} as required by the CRAN policies.  And
the package code uses clock_gettime in C++ but scrypt tested for it in C
(which does not need it to be declared in a header).
```

**Comment by bobjansen** [comment]
If I understand the message correctly, the compile issue has already been fixed:

https://github.com/rstudio/rscrypt/blob/master/src/util.cpp#L35

In any case, it compiles on Mac OSX El Capitan:

https://builder.r-hub.io/status/scrypt_0.1.2.tar.gz-450ede055b4e2075494a4b0b12f58caa

I've added configure.ac from the tarsnap/scrypt repo and recreated the files, see #14.

**Comment by bobjansen** [comment]
I have taken over.
